/**
 * Travelvus V2 — Airport Choice Hub Model
 *
 * Reusable data model for city-level airport choice hubs.
 * The hub is a discovery layer — it never calculates recommendations.
 * All decisions are generated by the existing Decision Engine.
 *
 * Phase 110.0 — Parts A+B.
 */

import type { CityId } from "@/data/cities";

/* ── Types ────────────────────────────────────────────────── */

export interface HubAirportCard {
  code: string;
  name: string;
  tagline: string;
  strengths: string[];
  watchOut: string[];
  bestFor: string;
}

export interface HubQuickFact {
  label: string;
  value: string;
  note?: string;
}

export interface HubScenario {
  id: string;
  title: string;
  description: string;
  suggestedWinner: string;
  prefilledParams: string;
  ctaLabel: string;
}

export interface HubComparisonLink {
  label: string;
  href: string;
  description: string;
}

export interface CityAirportHub {
  cityId: CityId;
  title: string;
  subtitle: string;
  heroDescription: string;
  airports: HubAirportCard[];
  quickFacts: HubQuickFact[];
  scenarios: HubScenario[];
  comparisonLinks: HubComparisonLink[];
  relatedGuides: { label: string; href: string }[];
  methodology: string;
  lastReviewed: string;
}

/* ── Helpers ──────────────────────────────────────────────── */

/** Build a compare URL for a city hub with prefilled params. */
export function buildHubCompareUrl(
  cityId: string,
  dest: string,
  overrides?: { aTicket?: number; bTicket?: number; bagRemoved?: boolean }
): string {
  const sp = new URLSearchParams();
  sp.set("city", cityId);
  sp.set("dest", dest);

  // Default ticket prices vary by city
  const defaults: Record<string, [number, number]> = {
    london: [58, 126],
    "new-york": [95, 110],
    paris: [80, 95],
  };
  const [defA, defB] = defaults[cityId] ?? [80, 95];
  sp.set("at", String(overrides?.aTicket ?? defA));
  sp.set("bt", String(overrides?.bTicket ?? defB));

  // Prefilled origin/destination
  const airportMap: Record<string, [string, string]> = {
    london: ["London · STN", "London · LHR"],
    "new-york": ["New York · JFK", "New York · EWR"],
    paris: ["Paris · CDG", "Paris · ORY"],
  };
  const [codeA, codeB] = airportMap[cityId] ?? ["", ""];

  sp.set("af", "Berlin · BER");
  sp.set("at2", codeA);
  sp.set("ad", "08:00");
  sp.set("aa", "10:00");
  sp.set("bf", "Berlin · BER");
  sp.set("bt2", codeB);
  sp.set("bd", "08:30");
  sp.set("ba", "10:30");

  return `/result?${sp.toString()}`;
}
