import type { Metadata } from "next";
import TrustPage from "@/components/ui/TrustPage";

export const metadata: Metadata = {
  title: "Editorial Standards — How We Maintain Accuracy | Travelvus",
  description: "Travelvus editorial standards: independence, accuracy, review process, corrections policy, and how we maintain trustworthy airport comparisons.",
};

export default function Page() {
  return (
    <TrustPage
      title="Editorial Standards"
      description="How we maintain accuracy, independence, and trust in every recommendation."
      lastReviewed="July 2026"
      sections={[
        {
          heading: "Editorial independence",
          body: "Travelvus is editorially independent. We do not accept payment for recommendations. No airport, airline, or transport operator can influence which option we recommend. Our recommendations are generated by the Decision Engine from public data — not by commercial partnerships. If an airport is recommended, it's because the data supports it — not because we were paid to say so.",
        },
        {
          heading: "Accuracy commitment",
          body: "We strive for factual accuracy in every transfer profile, every fare estimate, and every comparison. Transfer costs are based on official published fares from transport authorities. Journey times are based on official timetables with reasonable allowances for walking and waiting. When we use estimates (marked as 'illustrative' or 'estimate'), we say so clearly. When we have verified data (marked as 'strong' or 'verified'), we cite the source.",
        },
        {
          heading: "Review process",
          body: "Transfer profiles are reviewed at least quarterly or when significant changes occur (new train lines, fare revisions, service changes). Every dataset includes a source label, a source date, and a reviewed date. Our City Factory validator runs automated checks on every city dataset — verifying that all required transfer profiles exist, all costs are positive, and all metadata is present. No city goes live without passing all validator checks.",
        },
        {
          heading: "Update policy",
          body: "We update transfer profiles when: (1) Official fares change significantly. (2) New transport connections open (e.g., the Elizabeth Line in London, Metro 14 extension in Paris). (3) Service patterns change (e.g., Night Tube expansion). (4) Users report outdated information. Minor fare adjustments (less than ~5%) are batched into periodic reviews. Major changes are updated promptly.",
        },
        {
          heading: "Error correction policy",
          body: "If we discover an error in our data or recommendations, we correct it as quickly as possible. Corrections are noted in the page's review metadata. If a recommendation would have been different with correct data, we note that too. Users can report potential errors through our feedback mechanism on every page. We review all reports and respond to substantiated issues.",
        },
        {
          heading: "Transparency about limitations",
          body: "We are transparent about what our engine cannot do. Transfer times are estimates — actual journeys vary with traffic, disruption, and connection timing. Airfares are illustrative — live prices depend on dates, demand, and booking windows. We don't account for temporary disruptions like engineering works or strikes. Our Limitations page explains all of this in detail. We believe transparency about limitations builds more trust than pretending to have perfect information.",
        },
      ]}
    />
  );
}
